apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pyapp
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
     labels:
       app: pyapp
    spec:
      containers:
        - name: pyappc
          image: dockergeethaacc/pyhtonapp:1
          ports:
          - name: t
            containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pyappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: pyapp
  ports:
  - port: 80
    targetPort: t

